<?php $success=Session::flash('success'); $error=Session::flash('error'); ?>
<?php if($success): ?><div class="alert success"><?= h($success) ?></div><?php endif; ?>
<?php if($error): ?><div class="alert error"><?= h($error) ?></div><?php endif; ?>
<section class="page-heading"><div><p class="eyebrow">PAYROLL</p><h2>Payroll runs</h2><p class="muted">Create a monthly payroll draft, calculate employee pay, then move it through review and approval.</p></div><?php if($companies): ?><a class="button link-button" href="/payroll/create?company=<?= h($companyId) ?>">Create payroll</a><?php endif; ?></section>
<?php if($companies): ?>
<form method="get" class="selector-card card"><div class="selectors"><label>Company<select name="company" onchange="this.form.submit()"><?php foreach($companies as $company): $id=(string)($company['id']??''); ?><option value="<?= h($id) ?>" <?= $id===$companyId?'selected':'' ?>><?= h((string)($company['legal_name']??'Company')) ?></option><?php endforeach; ?></select></label></div></form>
<?php if($loadError): ?><div class="alert error"><?= h($loadError) ?></div><?php endif; ?>
<?php if($runs): ?><section class="table-card card"><div class="section-heading"><div><h2>Payroll history</h2><p class="muted">Each payroll run keeps its own employee and salary snapshot.</p></div></div><div class="table-wrap"><table><thead><tr><th>Period</th><th>Employees</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody><?php foreach($runs as $run): ?><tr><td><strong><?= h((string)($run['period']??'—')) ?></strong></td><td><?= h((string)($run['employee_count']??0)) ?></td><td><span class="status status-approved"><?= h((string)($run['status']??'DRAFT')) ?></span></td><td><?= h(isset($run['created_at']) ? date('d M Y H:i', strtotime((string)$run['created_at'])) : '—') ?></td><td><a class="text-link" href="/payroll/run?run=<?= rawurlencode((string)($run['id']??'')) ?>&company=<?= rawurlencode($companyId) ?>">Open →</a></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php else: ?><section class="empty card"><p class="eyebrow">NO PAYROLL RUNS</p><h2>Start a payroll for a month</h2><p class="muted">A payroll draft snapshots eligible employees before calculations are performed.</p><a class="button link-button" href="/payroll/create?company=<?= h($companyId) ?>">Create payroll</a></section><?php endif; ?>
<?php else: ?><section class="empty card"><p class="eyebrow">COMPANY REQUIRED</p><h2>Create a company first</h2><p class="muted">Payroll runs are always isolated within a company.</p><a class="button link-button" href="/companies/create">Create company</a></section><?php endif; ?>